/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Merged, useGLTF } from '@react-three/drei'
import React, { useMemo, useRef } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['book-1']: THREE.Mesh
    ['book-1_2']: THREE.Mesh
    ['book-3']: THREE.Mesh
    ['book-3001']: THREE.Mesh
    ['book-4']: THREE.Mesh
    ['book-4_2']: THREE.Mesh
    Cube: THREE.Mesh
    Cube_2: THREE.Mesh
    Cube_3: THREE.Mesh
    Cube_4: THREE.Mesh
    Cube_5001: THREE.Mesh
    Cube_8: THREE.Mesh
    Cube_6: THREE.Mesh
    Cube_7: THREE.Mesh
    Rectangle_4: THREE.Mesh
    Rectangle_5: THREE.Mesh
    Cube001: THREE.Mesh
    Rectangle_9: THREE.Mesh
    Cube_12: THREE.Mesh
    Cube_14: THREE.Mesh
    Cube_15: THREE.Mesh
    Cube_13: THREE.Mesh
    Cube_16: THREE.Mesh
    Cube_18: THREE.Mesh
    Cube_18002: THREE.Mesh
    Cube_17: THREE.Mesh
    Cube_18001: THREE.Mesh
  }
  materials: {
    Material_9: THREE.MeshStandardMaterial
    Material_5: THREE.MeshStandardMaterial
    Material_8: THREE.MeshStandardMaterial
    Material_13: THREE.MeshStandardMaterial
    Material_10: THREE.MeshStandardMaterial
    Material_11: THREE.MeshStandardMaterial
    Material_24: THREE.MeshStandardMaterial
    Material_23: THREE.MeshStandardMaterial
    Material_22: THREE.MeshStandardMaterial
    Material_19: THREE.MeshStandardMaterial
    Material_17: THREE.MeshStandardMaterial
  }
}

export default function Bookshelf(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/models/bookshelf-transformed.glb') as GLTFResult
  const instances = useMemo(
    () => ({
      Cube4: nodes.Cube_5001,
      Rectangle: nodes.Rectangle_4,
      Cube8: nodes.Cube_12,
      Cube9: nodes.Cube_13,
      Cube10: nodes.Cube_17,
    }),
    [nodes],
  )

  return (
    <Merged meshes={instances} {...props}>
      {(instances: any) => <Model instances={instances} />}
    </Merged>
  )
}

function Model({ instances, ...props }: JSX.IntrinsicElements['group'] & { instances: any }) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials } = useGLTF('/models/bookshelf-transformed.glb') as GLTFResult

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.78, 0]} scale={0.01}>
        <group position={[-3.18, 33.59, -4.76]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['book-1'].geometry}
            material={nodes['book-1'].material}
            position={[8.6, 27, -31.04]}
            rotation={[-Math.PI / 2, 0, -1.66]}
            scale={[0.22, 0.22, 0.22]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['book-1_2'].geometry}
            material={nodes['book-1_2'].material}
            position={[-9.38, 30.33, 32.4]}
            rotation={[-Math.PI / 2, 0, -1.46]}
            scale={0.25}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['book-3'].geometry}
            material={nodes['book-3'].material}
            position={[-10.76, 22.66, 31.84]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={0.25}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['book-3001'].geometry}
            material={materials.Material_13}
            position={[7.77, 19.82, -28.42]}
            rotation={[-Math.PI / 2, 0, -1.83]}
            scale={0.22}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['book-4'].geometry}
            material={nodes['book-4'].material}
            position={[-7.15, 38.27, 28.72]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={0.25}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['book-4_2'].geometry}
            material={nodes['book-4_2'].material}
            position={[-10.86, 17.52, 31.68]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={0.25}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube.geometry}
            material={nodes.Cube.material}
            position={[-14.29, -21.97, -41.63]}
            rotation={[0, -1.57, 0]}
            scale={[0.23, 0.23, 0.23]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_2.geometry}
            material={nodes.Cube_2.material}
            position={[-12.55, -27.15, -33.43]}
            rotation={[0, -1.57, 0]}
            scale={[0.23, 0.23, 0.23]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_3.geometry}
            material={nodes.Cube_3.material}
            position={[-9.44, -33.57, 12.83]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={0.23}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_4.geometry}
            material={nodes.Cube_4.material}
            position={[-10.08, -22.92, -26.93]}
            rotation={[0, -1.57, 0]}
            scale={[0.23, 0.23, 0.23]}
          />
          <instances.Cube4 position={[-15.94, -24.52, -11.14]} rotation={[0, -1.57, 0]} scale={[0.23, 0.23, 0.23]} />
          <instances.Cube4 position={[-12.55, -24.52, -19.82]} rotation={[0, -1.57, 0]} scale={[0.23, 0.23, 0.23]} />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_6.geometry}
            material={nodes.Cube_6.material}
            position={[-12.76, -39.11, 14.91]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={0.23}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_7.geometry}
            material={nodes.Cube_7.material}
            position={[-8.7, -24.84, 13.33]}
            rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
            scale={0.23}
          />
          <instances.Rectangle
            position={[1.51, 15.36, -21.86]}
            rotation={[-Math.PI / 2, 0, -2.27]}
            scale={[0.22, 0.22, 0.22]}
          />
          <instances.Rectangle
            position={[10.46, 15.92, -24.49]}
            rotation={[-Math.PI / 2, 0, -1.95]}
            scale={[0.22, 0.22, 0.22]}
          />
        </group>
        <group position={[-3.61, -47.66, 16.71]} rotation={[Math.PI, -0.04, Math.PI]} scale={[0.33, 0.3, 0.33]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube001.geometry}
            material={materials.Material_24}
            position={[-0.69, -0.53, -1.41]}
            scale={0.78}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_9.geometry}
            material={materials.Material_23}
            position={[57.6, -29.15, -12]}
            rotation={[0, 1.57, 0]}
          />
        </group>
        <group position={[4.37, -2.47, 2.29]} scale={0.28}>
          <instances.Cube8
            position={[1.56, 172.83, -13.49]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.97, 1, 1]}
          />
          <instances.Cube8
            position={[1.56, -28.42, -13.49]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.97, 1, 1]}
          />
          <instances.Cube8
            position={[1.56, -230.03, -13.49]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={[0.97, 1, 1]}
          />
          <instances.Cube9
            position={[-129.87, -9.93, 211.31]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1.09, 1.75, 1]}
          />
          <instances.Cube9
            position={[129.87, -9.93, 211.31]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1.09, 1.75, 1]}
          />
          <instances.Cube9
            position={[129.87, -9.93, -230.31]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1.09, 1.5, 1]}
          />
          <instances.Cube9
            position={[-129.87, -9.93, -230.31]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[1.09, 1.5, 1]}
          />
          <instances.Cube10
            position={[-2.46, 224.41, 211.31]}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={[1.07, 0.93, 0.95]}
          />
          <instances.Cube10
            position={[-2.46, 224.41, -230.31]}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={[1.07, 0.93, 0.95]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/bookshelf-transformed.glb')
