/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Merged_Geometry001: THREE.Mesh
    Rectangle_2: THREE.Mesh
  }
  materials: {
    Material_7: THREE.MeshStandardMaterial
    Material_6: THREE.MeshStandardMaterial
  }
}

export default function Artboard({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group | null>(null)
  const { nodes, materials } = useGLTF('/models/artboard-transformed.glb') as GLTFResult

  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 93.06, 0]}>
          <group position={[0, 3.78, 0]} rotation={[-2.75, -0.83, -2.8]} scale={[0.19, 0.19, 0.19]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Merged_Geometry001.geometry}
              material={materials.Material_7}
              position={[9.42, -22.11, 2.91]}
              rotation={[-2.94, 0.88, -3.07]}
              scale={5.3}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_2.geometry}
              material={materials.Material_6}
              position={[-2.45, 124.25, 31.44]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[0.95, 0.95, 0.95]}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/artboard-transformed.glb')
