/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.5 ./models/apple-tree.glb -t -T --shadows
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube_2011: THREE.Mesh
    Cube_3005: THREE.Mesh
    Cube_4010: THREE.Mesh
    Cylinder009: THREE.Mesh
  }
  materials: {
    Material_12: THREE.MeshStandardMaterial
    Material_84: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/apple-tree-transformed.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group position={[0, 5, 0]} scale={0.025}>
        <group position={[-13.22, -0.87, 35.04]} scale={0.81}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_2011.geometry}
            material={materials.Material_12}
            position={[56.5, 217.12, 7.05]}
            rotation={[0, 0, 0.26]}
            scale={1.3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_3005.geometry}
            material={materials.Material_12}
            position={[-95, 37.73, 2.12]}
            rotation={[0, 0, 0.69]}
            scale={1.3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_4010.geometry}
            material={materials.Material_12}
            position={[71.15, 52.19, -90.5]}
            rotation={[0.86, 0.99, 2.52]}
            scale={1.3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder009.geometry}
            material={materials.Material_84}
            position={[3.55, -112.04, -7.6]}
            scale={1.3}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/apple-tree-transformed.glb')
