/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.5 ./models/bed-cabinet.glb -t -T --shadows
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube_63005: THREE.Mesh
    Cube_64: THREE.Mesh
    Cube_65: THREE.Mesh
    Merged_Geometry_3: THREE.Mesh
    Rectangle_2002: THREE.Mesh
    Rectangle_3001: THREE.Mesh
    Rectangle003: THREE.Mesh
    Cylinder_2003: THREE.Mesh
    Cylinder_3001: THREE.Mesh
    Cylinder_4001: THREE.Mesh
    Cylinder_6: THREE.Mesh
  }
  materials: {
    Material_7: THREE.MeshStandardMaterial
    Material_2: THREE.MeshStandardMaterial
    Material_49: THREE.MeshStandardMaterial
    Material_71: THREE.MeshStandardMaterial
    Material_51: THREE.MeshStandardMaterial
    Material_0: THREE.MeshStandardMaterial
    Material_73: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/bed-cabinet-transformed.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.67, 0]} scale={0.01}>
        <group position={[0, -44.32, 0]} scale={[0.75, 1, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_63005.geometry}
            material={materials.Material_7}
            position={[0, 4.1, 0]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_64.geometry}
            material={materials.Material_2}
            position={[1.12, 4.1, 0]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_65.geometry}
            material={materials.Material_7}
            position={[0.4, 4.1, 0]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          />
        </group>
        <group position={[4.57, -4.13, 33.3]} rotation={[-Math.PI, 0.17, -Math.PI]} scale={0.19}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Merged_Geometry_3.geometry}
            material={materials.Material_2}
            position={[-46.13, -1.49, -4.63]}
            rotation={[Math.PI, -0.17, Math.PI]}
            scale={5.14}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_2002.geometry}
            material={materials.Material_49}
            position={[19.95, -0.51, 0]}
            rotation={[0, -1.57, 0]}
            scale={0.32}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_3001.geometry}
            material={materials.Material_71}
            position={[-13.66, 50.53, 64.18]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={0.32}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle003.geometry}
            material={materials.Material_51}
            position={[-45.16, -0.67, -1.26]}
            rotation={[0, -1.57, 0]}
            scale={0.32}
          />
        </group>
        <group position={[-14.47, -27.02, -43.61]} scale={0.78}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_2003.geometry}
            material={materials.Material_0}
            position={[-0.1, 20.93, 0.3]}
            scale={0.42}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_3001.geometry}
            material={materials.Material_0}
            position={[-0.22, 56.27, 0.66]}
            scale={0.42}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_4001.geometry}
            material={materials.Material_73}
            position={[0.1, 107.98, -0.3]}
            scale={0.42}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_6.geometry}
            material={materials.Material_0}
            position={[-0.09, 125.26, -0.3]}
            scale={0.42}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/bed-cabinet-transformed.glb')
