/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.5 ./models/cabinet.glb -t -T --shadows
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube_2006: THREE.Mesh
    Merged_Geometry_2003: THREE.Mesh
    Merged_Geometry017: THREE.Mesh
    Cube003: THREE.Mesh
    Cylinder_2002: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cylinder003: THREE.Mesh
    Rectangle_2001: THREE.Mesh
    红色: THREE.Mesh
  }
  materials: {
    Material_45: THREE.MeshStandardMaterial
    Material_41: THREE.MeshStandardMaterial
    Material_25: THREE.MeshStandardMaterial
    Material_27: THREE.MeshStandardMaterial
    Material_43: THREE.MeshStandardMaterial
    Material_38: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/cabinet-transformed.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.54, 0]} rotation={[0, 0, 0]} scale={0}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2006.geometry}
          material={materials.Material_45}
          position={[0, -49.69, -97.57]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[1, 0.88, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Merged_Geometry_2003.geometry}
          material={materials.Material_41}
          position={[-2.64, 12.06, 142.41]}
          rotation={[0, 1.57, 0]}
          scale={[5.06, 5.47, 6.11]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Merged_Geometry017.geometry}
          material={materials.Material_25}
          position={[-3.3, -46.08, 131.27]}
          rotation={[0, 1.57, 0]}
          scale={[5.06, 5.47, 6.11]}
        />
      </group>
      <group position={[3.91, 0.95, -0.98]} rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={materials.Material_27}
          position={[46.2, -124.61, 7.27]}
          rotation={[0, 0, -1.75]}
          scale={1.28}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_2002.geometry}
          material={materials.Material_27}
          position={[-89.13, -155.17, 5.27]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={1.28}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002.geometry}
          material={materials.Material_27}
          position={[86.56, -127.47, 7.09]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={1.28}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={materials.Material_27}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[0.72, 0.09, 0.72]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_2001.geometry}
          material={materials.Material_43}
          position={[4.53, -22.14, -42.46]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={1.28}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.红色.geometry}
          material={materials.Material_38}
          rotation={[-1.94, -1.51, 2.72]}
          scale={[0.72, 0.09, 0.72]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/cabinet-transformed.glb')
