/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.5 ./models/cabinet-bathroom.glb -t -T --shadows
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube_76: THREE.Mesh
    Cube_80: THREE.Mesh
    Cube_81: THREE.Mesh
    Cube_83: THREE.Mesh
    Cube_83001: THREE.Mesh
    Cube_83002: THREE.Mesh
    Cube_83003: THREE.Mesh
    Cube_86: THREE.Mesh
    Merged_Geometry_2005: THREE.Mesh
    Merged_Geometry032: THREE.Mesh
  }
  materials: {
    Material_0: THREE.MeshStandardMaterial
    Material_43: THREE.MeshStandardMaterial
    Material_54: THREE.MeshStandardMaterial
    Material_51: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/cabinet-bathroom-transformed.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.5, 0]} scale={0.025}>
        <group position={[-6.15, -18.73, 0]} scale={[1, 1.26, 1]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_76.geometry}
            material={materials.Material_0}
            position={[-4.16, 0, 0]}
            rotation={[0, 1.57, 0]}
            scale={[1, 0.79, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_80.geometry}
            material={materials.Material_0}
            position={[54.27, 17.41, 0.52]}
            rotation={[0, 1.57, 0]}
            scale={[1.12, 0.76, 0.18]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_81.geometry}
            material={materials.Material_0}
            position={[54.27, -16.27, 0.52]}
            rotation={[0, 1.57, 0]}
            scale={[1.12, 0.76, 0.18]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_83.geometry}
            material={materials.Material_0}
            position={[53.69, 1.25, -130.83]}
            rotation={[Math.PI, -Math.PI / 2, 0]}
            scale={[-1, -0.76, -1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_83001.geometry}
            material={materials.Material_0}
            position={[53.69, 1.25, 79.04]}
            rotation={[Math.PI, -Math.PI / 2, 0]}
            scale={[-1, -0.76, -1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_83002.geometry}
            material={materials.Material_0}
            position={[53.69, 1.25, -78.66]}
            rotation={[0, 1.57, 0]}
            scale={[1, 0.76, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_83003.geometry}
            material={materials.Material_0}
            position={[53.69, 1.25, 131.22]}
            rotation={[0, 1.57, 0]}
            scale={[1, 0.76, 1]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_86.geometry}
          material={materials.Material_43}
          position={[-6.87, 28.11, 0]}
          rotation={[0, 1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Merged_Geometry_2005.geometry}
          material={materials.Material_54}
          position={[51.13, -17.07, 0.19]}
          scale={[1, 1.26, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Merged_Geometry032.geometry}
          material={materials.Material_51}
          position={[53.43, -11.46, 0.19]}
          scale={[1, 1.26, 1]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/cabinet-bathroom-transformed.glb')
