/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.5 ./models/circle-table.glb -t -T --shadows
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder_10: THREE.Mesh
    Cylinder_11: THREE.Mesh
    Cylinder_12: THREE.Mesh
    Cylinder_9: THREE.Mesh
    Cylinder007: THREE.Mesh
    Merged_Geometry030: THREE.Mesh
  }
  materials: {
    Material_38: THREE.MeshStandardMaterial
    Material_74: THREE.MeshStandardMaterial
    Material_49: THREE.MeshStandardMaterial
    Material_0: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/circle-table-transformed.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.88, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_10.geometry}
          material={materials.Material_38}
          position={[3.08, 22.87, -0.84]}
          rotation={[2.95, 0.28, -2.92]}
          scale={0.19}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_11.geometry}
          material={materials.Material_38}
          position={[-0.49, 21.97, -2.67]}
          rotation={[-2.76, 0.79, 2.43]}
          scale={0.19}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_12.geometry}
          material={materials.Material_74}
          position={[2.54, -23.32, 0.22]}
          scale={0.42}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_9.geometry}
          material={materials.Material_49}
          position={[1.49, 2.91, -1.82]}
          rotation={[-Math.PI, 0.32, -Math.PI]}
          scale={0.12}
        />
      </group>
      <group position={[6.74, 0.29, -9.23]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007.geometry}
          material={materials.Material_0}
          position={[0, 26.09, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Merged_Geometry030.geometry}
          material={materials.Material_0}
          position={[0, -4.81, 1.12]}
          scale={1.3}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/circle-table-transformed.glb')
