/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.5 ./models/dinning-chair.glb -t -T --shadows
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube_95003: THREE.Mesh
    Merged_Geometry021: THREE.Mesh
    Shape_2003: THREE.Mesh
  }
  materials: {
    Material_7: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/dinning-chair-transformed.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.2, 0]} scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_95003.geometry}
          material={materials.Material_7}
          position={[0, 38.52, 24.29]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Merged_Geometry021.geometry}
          material={materials.Material_7}
          position={[0.22, -7.03, -2.47]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_2003.geometry}
          material={materials.Material_7}
          position={[-30.65, -5.65, -32.68]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/dinning-chair-transformed.glb')
