/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.5 ./models/double-bed.glb -t -T --shadows
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube_63006: THREE.Mesh
    Cube_64001: THREE.Mesh
    Cube_65001: THREE.Mesh
    Cube_67: THREE.Mesh
    Cube_68: THREE.Mesh
    Cube_69: THREE.Mesh
    Cube_70: THREE.Mesh
  }
  materials: {
    Material_2: THREE.MeshStandardMaterial
    Material_49: THREE.MeshStandardMaterial
    Material_0: THREE.MeshStandardMaterial
    Material_43: THREE.MeshStandardMaterial
    Material_25: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/double-bed-transformed.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.4, 0]} scale={0.022}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_63006.geometry}
          material={materials.Material_2}
          position={[14.35, -30.32, -0.27]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_64001.geometry}
          material={materials.Material_49}
          position={[62.36, -22.43, 1.2]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_65001.geometry}
          material={materials.Material_0}
          position={[-209.67, -0.68, -4.75]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_67.geometry}
          material={materials.Material_43}
          position={[-172.28, 21.84, -62.81]}
          rotation={[-Math.PI / 2, -0.61, 0]}
          scale={1.08}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_68.geometry}
          material={materials.Material_43}
          position={[-172.28, 21.84, 44.78]}
          rotation={[-Math.PI / 2, -0.61, 0]}
          scale={1.08}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_69.geometry}
          material={materials.Material_25}
          position={[-135.21, 26.93, -54.39]}
          rotation={[-Math.PI / 2, -1.13, 0]}
          scale={1.08}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_70.geometry}
          material={materials.Material_25}
          position={[-141.88, 23.18, 63.51]}
          rotation={[-2.08, -1.07, -0.56]}
          scale={1.08}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/double-bed-transformed.glb')
