/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.5 ./models/kitchen-rug.glb -t -T --shadows
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Merged_Geometry_10002: THREE.Mesh
    Merged_Geometry_11001: THREE.Mesh
    Rectangle_12001: THREE.Mesh
  }
  materials: {
    Material_52: THREE.MeshStandardMaterial
    Material_59: THREE.MeshStandardMaterial
    Material_54: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/kitchen-rug-transformed.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.01, 0]} scale={0.003}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Merged_Geometry_10002.geometry}
          material={materials.Material_52}
          position={[-10.29, 2.49, -0.37]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Merged_Geometry_11001.geometry}
          material={materials.Material_59}
          position={[12.47, 2.5, 39.04]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_12001.geometry}
          material={materials.Material_54}
          position={[0, -2.5, 0.39]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/kitchen-rug-transformed.glb')
