/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.5 ./models/kitchen-shelf.glb -t -T --shadows
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube_57001: THREE.Mesh
    Cube_57002: THREE.Mesh
    Cube_59003: THREE.Mesh
    Cube_60004: THREE.Mesh
    Cube_61002: THREE.Mesh
    Cube_62003: THREE.Mesh
    Cube_63004: THREE.Mesh
  }
  materials: {
    Material_7: THREE.MeshStandardMaterial
    Material_70: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/kitchen-shelf-transformed.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.17, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_57001.geometry}
          material={materials.Material_7}
          position={[51.11, -73.72, 0]}
          rotation={[0, 1.57, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_57002.geometry}
          material={materials.Material_70}
          position={[-1.06, -79.94, -8.38]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_59003.geometry}
          material={materials.Material_70}
          position={[-0.95, 6.32, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1.3, 0.91, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_60004.geometry}
          material={materials.Material_70}
          position={[-0.95, 53.74, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1.3, 0.91, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_61002.geometry}
          material={materials.Material_70}
          position={[0, 101.26, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1.32, 0.91, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_62003.geometry}
          material={materials.Material_70}
          position={[0, 111.04, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1.32, 0.91, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_63004.geometry}
          material={materials.Material_70}
          position={[52.05, -82.05, 0]}
          rotation={[0, 1.57, 0]}
          scale={[1.3, 0.91, 1]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/kitchen-shelf-transformed.glb')
