/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.5 ./models/kitchen-cabinet.glb -t -T --shadows
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder_31: THREE.Mesh
    Cylinder_32: THREE.Mesh
    Cylinder_33: THREE.Mesh
    Merged_Geometry026: THREE.Mesh
    Cube_45001: THREE.Mesh
    Cube_54001: THREE.Mesh
    Cube_46001: THREE.Mesh
    Cube_47001: THREE.Mesh
    Cube_50: THREE.Mesh
    Cube_50001: THREE.Mesh
    Cube_48001: THREE.Mesh
    Cube_49001: THREE.Mesh
    Cube_44001: THREE.Mesh
    Merged_Geometry025: THREE.Mesh
    Rectangle_4003: THREE.Mesh
    Rectangle_6002: THREE.Mesh
    Cube_7005: THREE.Mesh
    Cylinder_34002: THREE.Mesh
    Merged_Geometry027: THREE.Mesh
    Boolean: THREE.Mesh
    Cube_44: THREE.Mesh
    Cube_45: THREE.Mesh
    Cube_54: THREE.Mesh
    Cube_46: THREE.Mesh
    Cube_47: THREE.Mesh
    Cube_55: THREE.Mesh
    Cube_48: THREE.Mesh
    Cube_49: THREE.Mesh
    Cube_56: THREE.Mesh
    Merged_Geometry_11002: THREE.Mesh
    Rectangle_4002: THREE.Mesh
    Cube_4006: THREE.Mesh
    Cylinder_34004: THREE.Mesh
    Cube_41: THREE.Mesh
    Cylinder_34003: THREE.Mesh
    Merged_Geometry028: THREE.Mesh
    knife001: THREE.Mesh
    Rectangle_6003: THREE.Mesh
  }
  materials: {
    Material_46: THREE.MeshStandardMaterial
    Material_25: THREE.MeshStandardMaterial
    Material_27: THREE.MeshStandardMaterial
    Material_42: THREE.MeshStandardMaterial
    Material_71: THREE.MeshStandardMaterial
    Material_7: THREE.MeshStandardMaterial
    Material_60: THREE.MeshStandardMaterial
    Material_52: THREE.MeshStandardMaterial
    Material_51: THREE.MeshStandardMaterial
    Material_6: THREE.MeshStandardMaterial
    Material_50: THREE.MeshStandardMaterial
    Material_43: THREE.MeshStandardMaterial
    Material_38: THREE.MeshStandardMaterial
    Material_40: THREE.MeshStandardMaterial
    Material_65: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/kitchen-cabinet-transformed.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.7, 0]} scale={0.01}>
        <group position={[73.78, 0, -151.09]}>
          <group position={[-88.89, 45.19, -3.96]} scale={0.93}>
            <group position={[0, 3.27, 0]} rotation={[0, 1.57, 0]} scale={0.21}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_31.geometry}
                material={materials.Material_46}
                position={[0, -25.29, 0]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_32.geometry}
                material={materials.Material_46}
                position={[0, 69.81, 0]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_33.geometry}
                material={materials.Material_25}
                position={[0, 91.29, 0]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Merged_Geometry026.geometry}
              material={materials.Material_27}
              position={[0.11, -23, 0.51]}
              scale={1.08}
            />
          </group>
          <group position={[0, -23.51, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_45001.geometry}
              material={materials.Material_42}
              position={[22.86, -0.64, 62.73]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[0.18, 0.18, 0.16]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_54001.geometry}
              material={materials.Material_42}
              position={[-0.31, -0.64, 62.73]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[0.18, 0.18, 0.16]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_46001.geometry}
              material={materials.Material_71}
              position={[-94.14, 14.56, 49.15]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[0.99, 1, 0.92]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_47001.geometry}
              material={materials.Material_71}
              position={[-94.14, -25.21, 49.15]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[0.99, 1, 0.92]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_50.geometry}
              material={materials.Material_71}
              position={[101.6, -25.21, 49.15]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[0.66, 1, 0.92]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_50001.geometry}
              material={materials.Material_71}
              position={[101.6, 14.56, 49.15]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[0.66, 1, 0.92]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_48001.geometry}
              material={materials.Material_71}
              position={[-17.07, -5.11, 49.15]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[0.99, 1, 0.92]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_49001.geometry}
              material={materials.Material_71}
              position={[40.34, -5.11, 49.15]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[0.99, 1, 0.92]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_44001.geometry}
              material={materials.Material_71}
              position={[-4.29, -5.19, -15.17]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Merged_Geometry025.geometry}
              material={materials.Material_7}
              position={[2.16, -1.92, 54.35]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_4003.geometry}
              material={materials.Material_60}
              position={[0, 35.46, -12.5]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rectangle_6002.geometry}
              material={materials.Material_52}
              position={[-42.5, 43.32, -0.83]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
          <group position={[-10.34, 38.93, -3.65]} rotation={[0, 1.57, 0]} scale={0.2}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_7005.geometry}
              material={materials.Material_51}
              position={[5.76, -40.19, 6.61]}
              rotation={[-Math.PI / 2, 0, -0.61]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_34002.geometry}
              material={materials.Material_27}
              position={[-94.29, -44.62, 155.64]}
              rotation={[-Math.PI / 2, 0, -0.61]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Merged_Geometry027.geometry}
              material={materials.Material_27}
              position={[-0.84, -75.64, 0.12]}
              rotation={[0, -1.57, 0]}
              scale={5.01}
            />
          </group>
        </group>
        <group position={[-138.48, -24.44, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Boolean.geometry}
            material={materials.Material_6}
            position={[-7.5, 20.32, 180.45]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_44.geometry}
            material={materials.Material_71}
            position={[-7.5, -24.64, 180.45]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_45.geometry}
            material={materials.Material_42}
            position={[82.52, 0.29, -50.19]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[0.18, 0.18, 0.16]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_54.geometry}
            material={materials.Material_42}
            position={[82.52, 0.29, -27.03]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[0.18, 0.18, 0.16]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_46.geometry}
            material={materials.Material_71}
            position={[68.69, 15.48, 73.44]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={[1.14, 0.94, 0.92]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_47.geometry}
            material={materials.Material_71}
            position={[68.69, -24.28, 73.44]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={[1.14, 0.94, 0.92]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_55.geometry}
            material={materials.Material_71}
            position={[68.93, -24.28, 178.44]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={[0.99, 1, 0.92]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_48.geometry}
            material={materials.Material_71}
            position={[68.93, -4.18, -10.26]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={[0.99, 1, 0.92]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_49.geometry}
            material={materials.Material_71}
            position={[68.93, -4.18, -67.67]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={[0.99, 1, 0.92]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_56.geometry}
            material={materials.Material_71}
            position={[-7.5, -4.27, -38.2]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Merged_Geometry_11002.geometry}
            material={materials.Material_7}
            position={[74.14, -0.99, 128.69]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_4002.geometry}
            material={materials.Material_60}
            position={[-4.61, 36.39, -3.29]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          />
        </group>
        <group position={[-154.68, 41.89, -17.75]}>
          <group position={[-21.44, 1.34, -128.43]} rotation={[Math.PI, -0.09, Math.PI]} scale={0.24}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_4006.geometry}
              material={materials.Material_50}
              position={[0, -13.48, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_34004.geometry}
              material={materials.Material_6}
              position={[-0.68, 74.98, -0.24]}
            />
          </group>
          <group position={[-8.77, 0.09, 100.34]} rotation={[0, 1.57, 0]} scale={0.21}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_41.geometry}
              material={materials.Material_43}
              position={[0.6, -25.18, 1.86]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1.12, 1.12, 0.84]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_34003.geometry}
              material={materials.Material_7}
              position={[0, -93.28, 0]}
              rotation={[0, Math.PI / 9, 0]}
              scale={1.07}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Merged_Geometry028.geometry}
              material={materials.Material_38}
              position={[0.6, -26.47, 1.86]}
              rotation={[0, -1.57, 0]}
              scale={4.65}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.knife001.geometry}
            material={materials.Material_40}
            position={[18.94, -18.46, -91.1]}
            rotation={[-Math.PI / 2, 0, 1.31]}
            scale={0.21}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_6003.geometry}
            material={materials.Material_65}
            position={[12.03, -22.09, -9.11]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/kitchen-cabinet-transformed.glb')
