/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.5 ./models/leather-sofa.glb -t -T --shadows
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube_59004: THREE.Mesh
    Cube_63008: THREE.Mesh
    Cube_60005: THREE.Mesh
    Cube_63007: THREE.Mesh
    Cube_64002: THREE.Mesh
    Cube_65002: THREE.Mesh
    Cube_67001: THREE.Mesh
    Cube_66: THREE.Mesh
  }
  materials: {
    Material_56: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/leather-sofa-transformed.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.7, 0]} rotation={[0, 0, 0]} scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_59004.geometry}
          material={materials.Material_56}
          position={[23.91, -26.12, -67.03]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[1.42, 0.81, 1.37]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_63008.geometry}
          material={materials.Material_56}
          position={[-44.03, 9.64, -67.03]}
          rotation={[-Math.PI / 2, 1.13, -Math.PI / 2]}
          scale={[1.42, 0.81, 0.94]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_60005.geometry}
          material={materials.Material_56}
          position={[23.91, -26.12, 68.26]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[1.42, 0.81, 1.37]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_63007.geometry}
          material={materials.Material_56}
          position={[-44.03, 9.64, 68.26]}
          rotation={[-Math.PI / 2, 1.13, -Math.PI / 2]}
          scale={[1.42, 0.81, 0.94]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_64002.geometry}
          material={materials.Material_56}
          position={[23.91, -51, -1.91]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[1.17, 0.81, 1.37]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_65002.geometry}
          material={materials.Material_56}
          position={[9.19, -18.23, 144.64]}
          rotation={[Math.PI, 0, -Math.PI / 2]}
          scale={[1.17, 0.81, 1.37]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_67001.geometry}
          material={materials.Material_56}
          position={[9.19, -18.23, -147.01]}
          rotation={[Math.PI, 0, -Math.PI / 2]}
          scale={[1.17, 0.81, 1.37]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_66.geometry}
          material={materials.Material_56}
          position={[-53.31, -28.69, -1.24]}
          rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
          scale={[1.17, 0.81, 1.37]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/leather-sofa-transformed.glb')
