/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.5 ./models/one-leg-lamp.glb -t -T --shadows
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder_4: THREE.Mesh
    Cylinder_5: THREE.Mesh
    Cylinder004: THREE.Mesh
    Merged_Geometry010: THREE.Mesh
  }
  materials: {
    Material_25: THREE.MeshStandardMaterial
    Material_7: THREE.MeshStandardMaterial
    Material_51: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/one-leg-lamp-transformed.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.82, 0]} rotation={[Math.PI, 0, Math.PI]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_4.geometry}
          material={materials.Material_25}
          position={[2.48, -78.61, 1.11]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_5.geometry}
          material={materials.Material_7}
          position={[-28.92, 74.08, 0]}
          rotation={[0, 0, -0.09]}
          scale={0.74}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004.geometry}
          material={materials.Material_25}
          position={[-29.77, 64.45, 0]}
          rotation={[0, 0, -0.09]}
          scale={0.74}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Merged_Geometry010.geometry}
          material={materials.Material_51}
          position={[23.46, -6.63, 1.44]}
          rotation={[-Math.PI, 0.87, -Math.PI]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/one-leg-lamp-transformed.glb')
