/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.5 ./models/pattern-rug.glb -t -T --shadows
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Merged_Geometry_10001: THREE.Mesh
    Merged_Geometry_11: THREE.Mesh
    Merged_Geometry_12: THREE.Mesh
    Merged_Geometry_13: THREE.Mesh
    Merged_Geometry_14: THREE.Mesh
    Merged_Geometry_15: THREE.Mesh
    Rectangle_16: THREE.Mesh
    Rectangle_17: THREE.Mesh
  }
  materials: {
    Material_50: THREE.MeshStandardMaterial
    Material_27: THREE.MeshStandardMaterial
    Material_56: THREE.MeshStandardMaterial
    Material_55: THREE.MeshStandardMaterial
    Material_54: THREE.MeshStandardMaterial
    Material_51: THREE.MeshStandardMaterial
    Material_57: THREE.MeshStandardMaterial
    Material_53: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/pattern-rug-transformed.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Merged_Geometry_10001.geometry}
          material={materials.Material_50}
          position={[0.07, 2.27, 1.77]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Merged_Geometry_11.geometry}
          material={materials.Material_27}
          position={[32.21, 2.27, -29.61]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Merged_Geometry_12.geometry}
          material={materials.Material_56}
          position={[0.22, 2.27, 0.41]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Merged_Geometry_13.geometry}
          material={materials.Material_55}
          position={[-0.77, 2.27, 27.79]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Merged_Geometry_14.geometry}
          material={materials.Material_54}
          position={[-48.62, 2.26, 85.28]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Merged_Geometry_15.geometry}
          material={materials.Material_51}
          position={[-48.62, -0.02, 0.1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_16.geometry}
          material={materials.Material_57}
          position={[1.17, -2.29, 0.1]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_17.geometry}
          material={materials.Material_53}
          position={[112.81, -2.29, 0.1]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/pattern-rug-transformed.glb')
