/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.5 ./models/refrigerator.glb -t -T --shadows
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder_34005: THREE.Mesh
    Cylinder_35001: THREE.Mesh
    Cylinder_36: THREE.Mesh
    Cube_44002: THREE.Mesh
    Rectangle_8002: THREE.Mesh
    Cube_8005: THREE.Mesh
    Rectangle_7001: THREE.Mesh
    Boolean001: THREE.Mesh
    Rectangle_4004: THREE.Mesh
    Rectangle_5003: THREE.Mesh
  }
  materials: {
    Material_65: THREE.MeshStandardMaterial
    Material_41: THREE.MeshStandardMaterial
    Material_60: THREE.MeshStandardMaterial
    Material_42: THREE.MeshStandardMaterial
    Material_72: THREE.MeshStandardMaterial
    Material_7: THREE.MeshStandardMaterial
    Material_49: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/refrigerator-transformed.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.98, 0]} scale={0.01}>
        <group position={[6.42, 48.09, -19.83]} rotation={[Math.PI, 0, Math.PI]} scale={0.16}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_34005.geometry}
            material={materials.Material_65}
            position={[0, -94.07, 0]}
            rotation={[0, 0.96, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_35001.geometry}
            material={materials.Material_41}
            position={[0, -29.41, 0]}
            rotation={[0, 0.96, 0]}
            scale={[1, 0.79, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_36.geometry}
            material={materials.Material_60}
            position={[-1.38, 29.29, -0.96]}
            rotation={[0, 0.96, 0]}
            scale={[1, 0.79, 1]}
          />
        </group>
        <group position={[6.18, -37.07, 29.8]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_44002.geometry}
            material={materials.Material_42}
            position={[39.19, 33.1, 16.58]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.18, 0.18, 0.16]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_8002.geometry}
            material={materials.Material_42}
            position={[0, 0, -11.38]}
            scale={[0.21, 0.21, 0.19]}
          />
        </group>
        <group position={[-48.49, 61.88, 18.41]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_8005.geometry}
            material={materials.Material_42}
            position={[93.86, 1.83, 27.97]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.18, 0.18, 0.16]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rectangle_7001.geometry}
            material={materials.Material_42}
            position={[54.59, 0, 0.01]}
            scale={[0.21, 0.21, 0.19]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Boolean001.geometry}
          material={materials.Material_72}
          position={[6.1, 0, -25.47]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_4004.geometry}
          material={materials.Material_7}
          position={[-4.24, 52.09, 32.95]}
          rotation={[0, 0, 0.17]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_5003.geometry}
          material={materials.Material_49}
          position={[-10.43, 54.08, 33.44]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/refrigerator-transformed.glb')
