/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.5 ./models/relax-chair.glb -t -T --shadows
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube_60002: THREE.Mesh
    Cube_63: THREE.Mesh
    Merged_Geometry012: THREE.Mesh
  }
  materials: {
    Material_52: THREE.MeshStandardMaterial
    Material_41: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/relax-chair-transformed.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.54, 0]} rotation={[0, 0, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_60002.geometry}
          material={materials.Material_52}
          position={[30.78, -13.7, -0.42]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[1.31, 0.81, 1.37]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_63.geometry}
          material={materials.Material_52}
          position={[-35.5, 33.58, -0.44]}
          rotation={[-Math.PI / 2, 1.13, -Math.PI / 2]}
          scale={[1.31, 0.81, 0.94]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Merged_Geometry012.geometry}
          material={materials.Material_41}
          position={[-3.38, -10.75, 1.12]}
          rotation={[0, 1.13, 0]}
          scale={1.34}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/relax-chair-transformed.glb')
