/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.5 ./models/shiba.glb -t -T --shadows
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube_2009: THREE.Mesh
    Cube_2010: THREE.Mesh
    Cube009: THREE.Mesh
    Sphere_2002: THREE.Mesh
    Subdiv_2: THREE.Mesh
    Sphere_3001: THREE.Mesh
    Sphere_4001: THREE.Mesh
    Sphere002: THREE.Mesh
    Subdiv: THREE.Mesh
    Subdiv001: THREE.Mesh
    Cube_6003: THREE.Mesh
    Cube_7006: THREE.Mesh
    Cube_8006: THREE.Mesh
    Subdiv_8: THREE.Mesh
    Cylinder_13003: THREE.Mesh
    Merged_Geometry038: THREE.Mesh
    Shape_2007: THREE.Mesh
    Subdiv_10: THREE.Mesh
    Subdiv_9: THREE.Mesh
  }
  materials: {
    Material_87: THREE.MeshStandardMaterial
    Material_89: THREE.MeshStandardMaterial
    Material_85: THREE.MeshStandardMaterial
    Material_86: THREE.MeshStandardMaterial
    Material_38: THREE.MeshStandardMaterial
    Material_51: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/shiba-transformed.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.41, 0]} rotation={[-0.22, -0.08, 0.06]} scale={0.01}>
        <group position={[20.24, 17.1, 9.43]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_2009.geometry}
            material={materials.Material_87}
            position={[-16.35, 13.76, -8.03]}
            rotation={[-0.03, 0.12, -0.03]}
            scale={0.14}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_2010.geometry}
            material={materials.Material_87}
            position={[14.16, 12.68, -11.65]}
            rotation={[3.11, -0.12, 0.03]}
            scale={-0.14}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube009.geometry}
            material={materials.Material_87}
            position={[-0.24, 0.4, -2.89]}
            rotation={[-0.04, 0.12, -0.03]}
            scale={0.14}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere_2002.geometry}
            material={materials.Material_89}
            position={[11.58, 2.88, 13.8]}
            rotation={[-0.41, 0.37, 0.02]}
            scale={[0.14, 0.14, 0.15]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Subdiv_2.geometry}
            material={materials.Material_89}
            position={[-6.74, 3.8, 16.73]}
            rotation={[2.7, 0.04, 3.06]}
            scale={[0.14, 0.14, 0.15]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere_3001.geometry}
            material={materials.Material_85}
            position={[7.63, 12.72, 8.93]}
            rotation={[-0.93, 0.23, 0.31]}
            scale={[0.08, 0.08, 0.03]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere_4001.geometry}
            material={materials.Material_85}
            position={[-5.2, 12.9, 10.06]}
            rotation={[-0.96, -0.13, 0.29]}
            scale={[0.08, 0.08, 0.03]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere002.geometry}
            material={materials.Material_89}
            position={[3.45, -1.36, 25.08]}
            rotation={[-0.03, 0.12, -0.03]}
            scale={[0.14, 0.12, 0.14]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Subdiv.geometry}
            material={materials.Material_85}
            position={[14.23, 12.7, -11.11]}
            rotation={[3.11, -0.12, 0.03]}
            scale={-0.14}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Subdiv001.geometry}
            material={materials.Material_85}
            position={[-16.28, 13.78, -7.48]}
            rotation={[-0.03, 0.12, -0.03]}
            scale={0.14}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_6003.geometry}
          material={materials.Material_86}
          position={[-7.11, -14.77, -23.75]}
          rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
          scale={0.14}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_7006.geometry}
          material={materials.Material_86}
          position={[-23.24, -25.13, -41]}
          rotation={[2.32, 0.99, -2.64]}
          scale={0.15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_8006.geometry}
          material={materials.Material_86}
          position={[23.64, -24.37, -13.54]}
          rotation={[-2.74, 0.74, 2.84]}
          scale={0.14}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Subdiv_8.geometry}
          material={materials.Material_86}
          position={[2.99, -21.56, 4.53]}
          rotation={[2.92, 0.86, -2.81]}
          scale={[0.14, 0.16, 0.14]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_13003.geometry}
          material={materials.Material_38}
          position={[12.96, 3.71, -3.77]}
          rotation={[-3.02, 0.86, -2.43]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Merged_Geometry038.geometry}
          material={materials.Material_85}
          position={[0.32, -16.7, -18.3]}
          rotation={[0.22, 0.06, -0.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_2007.geometry}
          material={materials.Material_51}
          position={[13.59, -12, 8.66]}
          rotation={[0, 0.44, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Subdiv_10.geometry}
          material={materials.Material_86}
          position={[-25.82, -25.09, -20.78]}
          rotation={[-3.04, 1.08, -3]}
          scale={0.14}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Subdiv_9.geometry}
          material={materials.Material_86}
          position={[-1.13, -24.98, -38.31]}
          rotation={[-Math.PI, Math.PI / 4, 3.12]}
          scale={0.14}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/shiba-transformed.glb')
