/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.5 ./models/sofa.glb -t -T --shadows
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube_57: THREE.Mesh
    Cube_58001: THREE.Mesh
    Cube_63003: THREE.Mesh
    Cube_59002: THREE.Mesh
    Cube_63002: THREE.Mesh
    Cube_60003: THREE.Mesh
    Cube_63001: THREE.Mesh
    Cube_62002: THREE.Mesh
    Cube_71: THREE.Mesh
    Cube_72: THREE.Mesh
  }
  materials: {
    Material_50: THREE.MeshStandardMaterial
    Material_58: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/sofa-transformed.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.4, 0]} scale={0.023}>
        <group position={[4.48, 1.34, 0]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_57.geometry}
            material={materials.Material_50}
            position={[-7.05, -57.44, 0]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_58001.geometry}
            material={materials.Material_50}
            position={[-19.54, -32.84, 111.47]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={[1.17, 0.81, 1.37]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_63003.geometry}
            material={materials.Material_50}
            position={[48.4, 2.92, 111.47]}
            rotation={[-Math.PI / 2, -1.13, Math.PI / 2]}
            scale={[1.17, 0.81, 0.94]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_59002.geometry}
            material={materials.Material_50}
            position={[-19.54, -32.84, -0.04]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={[1.17, 0.81, 1.37]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_63002.geometry}
            material={materials.Material_50}
            position={[48.4, 2.92, -0.04]}
            rotation={[-Math.PI / 2, -1.13, Math.PI / 2]}
            scale={[1.17, 0.81, 0.94]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_60003.geometry}
            material={materials.Material_50}
            position={[-19.54, -32.84, -111.55]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={[1.17, 0.81, 1.37]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_63001.geometry}
            material={materials.Material_50}
            position={[48.4, 2.92, -111.55]}
            rotation={[-Math.PI / 2, -1.13, Math.PI / 2]}
            scale={[1.17, 0.81, 0.94]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube_62002.geometry}
            material={materials.Material_50}
            position={[54.37, -22.33, -1.51]}
            rotation={[Math.PI / 2, 1.4, -Math.PI / 2]}
            scale={[1.15, 0.76, 1]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_71.geometry}
          material={materials.Material_58}
          position={[-18.21, 13.98, -61.9]}
          rotation={[-1.4, -0.87, 0]}
          scale={1.08}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_72.geometry}
          material={materials.Material_58}
          position={[-21.4, 8.13, 86.88]}
          rotation={[-1.79, -0.83, -0.17]}
          scale={1.08}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/sofa-transformed.glb')
