/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.5 ./models/triangle-pattern-rug.glb -t -T --shadows
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Merged_Geometry_10003: THREE.Mesh
    Merged_Geometry_11003: THREE.Mesh
    Merged_Geometry_12001: THREE.Mesh
    Rectangle_12002: THREE.Mesh
  }
  materials: {
    Material_53: THREE.MeshStandardMaterial
    Material_41: THREE.MeshStandardMaterial
    Material_43: THREE.MeshStandardMaterial
    Material_59: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/triangle-pattern-rug-transformed.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.01, 0]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Merged_Geometry_10003.geometry}
          material={materials.Material_53}
          position={[-0.26, 2.7, 1.81]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Merged_Geometry_11003.geometry}
          material={materials.Material_41}
          position={[-0.26, 2.69, -0.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Merged_Geometry_12001.geometry}
          material={materials.Material_43}
          position={[-29.66, 2.71, -42.85]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Rectangle_12002.geometry}
          material={materials.Material_59}
          position={[0.19, -2.71, 0.5]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/triangle-pattern-rug-transformed.glb')
