import { Space as SpaceType } from '@/stores/dashboard'

export const mySpacesFromApi: SpaceType[] = [
  {
    id: '1',
    title: 'Nguyen Son Ha Wedding 1',
    subtitle: 'Edited 14 hours ago',
    imageUrl: 'https://hips.hearstapps.com/hmg-prod/images/womanyellingcat-1573233850.jpg',
    timeStamp: 1614556800000,
    author: 'Tien Thinh',
    category: 'families',
  },
  {
    id: '2',
    title: 'Nguyen Son Ha Wedding 2',
    subtitle: 'Edited 14 hours ago',
    imageUrl: 'https://hips.hearstapps.com/hmg-prod/images/womanyellingcat-1573233850.jpg',
    timeStamp: 1614643200000,
    author: 'Tien Thinh',
    category: 'families',
  },
  {
    id: '3',
    title: 'Nguyen Son Ha Wedding 3',
    subtitle: 'Edited 14 hours ago',
    imageUrl: 'https://hips.hearstapps.com/hmg-prod/images/womanyellingcat-1573233850.jpg',
    timeStamp: 1614729600000,
    author: 'Tien Thinh',
    category: 'families',
  },
  {
    id: '4',
    title: 'Nguyen Son Ha Wedding 4',
    subtitle: 'Edited 14 hours ago',
    imageUrl: 'https://hips.hearstapps.com/hmg-prod/images/womanyellingcat-1573233850.jpg',
    timeStamp: 1614816000000,
    author: 'Tien Thinh',
    category: 'families',
  },
  {
    id: '13',
    title: 'Nguyen Son Ha Wedding',
    subtitle: 'Edited 14 hours ago',
    imageUrl: 'https://www.boredpanda.com/blog/wp-content/uploads/2022/09/cat-memes-catslovecatnip-cover_800.png',
    timeStamp: 1614902400000,
    author: 'Tien Thinh',
    category: 'families',
  },
]

export const exploreSpacesFromApi: SpaceType[] = [
  {
    id: '5',
    title: 'Nguyen Son Ha Wedding',
    subtitle: 'Edited 14 hours ago',
    imageUrl: 'https://hips.hearstapps.com/hmg-prod/images/womanyellingcat-1573233850.jpg',
    timeStamp: 1614556800000,
    author: 'Tien Thinh',
    category: 'families',
  },
  {
    id: '6',
    title: 'Nguyen Son Ha Wedding',
    subtitle: 'Edited 14 hours ago',
    imageUrl: 'https://hips.hearstapps.com/hmg-prod/images/womanyellingcat-1573233850.jpg',
    timeStamp: 1614556800000,
    author: 'Tien Thinh',
    category: 'families',
  },
  {
    id: '7',
    title: 'Nguyen Son Ha Wedding',
    subtitle: 'Edited 14 hours ago',
    imageUrl: 'https://hips.hearstapps.com/hmg-prod/images/womanyellingcat-1573233850.jpg',
    timeStamp: 1614556800000,
    author: 'Tien Thinh',
    category: 'families',
  },
  {
    id: '8',
    title: 'Nguyen Son Ha Wedding',
    subtitle: 'Edited 14 hours ago',
    imageUrl: 'https://hips.hearstapps.com/hmg-prod/images/womanyellingcat-1573233850.jpg',
    timeStamp: 1614556800000,
    author: 'Tien Thinh',
    category: 'families',
  },
  {
    id: '9',
    title: 'Nguyen Son Ha Wedding',
    subtitle: 'Edited 14 hours ago',
    imageUrl: 'https://hips.hearstapps.com/hmg-prod/images/womanyellingcat-1573233850.jpg',
    timeStamp: 1614556800000,
    author: 'Tien Thinh',
    category: 'families',
  },
  {
    id: '10',
    title: 'Nguyen Son Ha Wedding',
    subtitle: 'Edited 14 hours ago',
    imageUrl: 'https://hips.hearstapps.com/hmg-prod/images/womanyellingcat-1573233850.jpg',
    timeStamp: 1614556800000,
    author: 'Tien Thinh',
    category: 'families',
  },
  {
    id: '11',
    title: 'Nguyen Son Ha Wedding',
    subtitle: 'Edited 14 hours ago',
    imageUrl: 'https://hips.hearstapps.com/hmg-prod/images/womanyellingcat-1573233850.jpg',
    timeStamp: 1614556800000,
    author: 'Tien Thinh',
    category: 'families',
  },
  {
    id: '12',
    title: 'Nguyen Son Ha Wedding',
    subtitle: 'Edited 14 hours ago',
    imageUrl: 'https://hips.hearstapps.com/hmg-prod/images/womanyellingcat-1573233850.jpg',
    timeStamp: 1614556800000,
    author: 'Tien Thinh',
    category: 'families',
  },
]

export const librariesSpacesFromApi: SpaceType[] = [
  {
    id: '14',
    title: 'Nguyen Son Ha Wedding',
    subtitle: 'Edited 14 hours ago',
    imageUrl: 'https://hips.hearstapps.com/hmg-prod/images/womanyellingcat-1573233850.jpg',
    timeStamp: 1614556800000,
    author: 'Son Ha',
    category: 'offices',
  },
  {
    id: '15',
    title: 'Tien Thinh Home',
    subtitle: 'Edited 14 hours ago',
    imageUrl: 'https://www.boredpanda.com/blog/wp-content/uploads/2022/09/cat-memes-catslovecatnip-cover_800.png',
    timeStamp: 1614556800000,
    author: 'Tien Thinh',
    category: 'families',
  },
  {
    id: '16',
    title: 'Tien Thinh Home',
    subtitle: 'Edited 14 hours ago',
    imageUrl: 'https://www.boredpanda.com/blog/wp-content/uploads/2022/09/cat-memes-catslovecatnip-cover_800.png',
    timeStamp: 1614556800000,
    author: 'Tien Thinh',
    category: 'families',
  },
  {
    id: '17',
    title: 'Tien Thinh Home',
    subtitle: 'Edited 14 hours ago',
    imageUrl: 'https://www.boredpanda.com/blog/wp-content/uploads/2022/09/cat-memes-catslovecatnip-cover_800.png',
    timeStamp: 1614556800000,
    author: 'Tien Thinh',
    category: 'families',
  },
  {
    id: '18',
    title: 'Tien Thinh Home',
    subtitle: 'Edited 14 hours ago',
    imageUrl: 'https://www.boredpanda.com/blog/wp-content/uploads/2022/09/cat-memes-catslovecatnip-cover_800.png',
    timeStamp: 1614556800000,
    author: 'Tien Thinh',
    category: 'families',
  },
  {
    id: '19',
    title: 'Tien Thinh Home',
    subtitle: 'Edited 14 hours ago',
    imageUrl: 'https://www.boredpanda.com/blog/wp-content/uploads/2022/09/cat-memes-catslovecatnip-cover_800.png',
    timeStamp: 1614556800000,
    author: 'Tien Thinh',
    category: 'families',
  },
]
